### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by ghost** [Taskeren/mineQuery-1.17#10]
HarvestX
Disables destroying immature crops, the bottom block of cactus/sugar cane, and pumpkin/melon stems.

Replanting
Automatic replants crops on harvest with the seed held in your hand. Depends on HarvestX. 

NotHit
Disables attacking Villagers and Iron Golems.

AutoRevive
Automatically respawns on death

Calculation Command
Calculates equations automatically using '/= {expression}' 

Location Convert Command
Uses '/localc <toNether/toOverworld> <x> <y> <z>' to convert coordinates from different dimensions.

Key2Cmd
Set a keybind to send a command or message.

NotPlace!
Use a stick named 'NotPlace' to enable/disable placing on the sides of a block. Useful for Skyblock players trying to place a floor.

Feed'em
Right-clicks all animals nearby when you shift. Can be used for breeding animals, or shearing sheep.

**Comment by Taskeren** [comment]
Updated the description in Modrinth and README.
Thanks for contributing!
