### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#12]
Is this planned? I'm still using this in 1.19.3 because useful mods like this have not updated to 1.19.4
While 1.19.4 seems to be improving alot in game performance so I would like to see this mod supporting 1.19.4

If you can't then I can understand, thanks.

**Comment by Taskeren** [comment]
The new release has been published at both Github Release and Modrinth.
Thanks for requesting. I've almost forget this project, as I'm no longer playing vanilla at all. lol

<https://modrinth.com/mod/minequery/version/1.7.4>

**Comment by Scarlaid** [comment]
I still like this mod's purpose so yeah, glad you remembered :D
