### ISSUE TITLE
1.19.4 backport

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#14]
As the title stated, I'm still on 1.19.4, might be the same with others existing out there because unsupported mods for 1.20

**Comment by Scarlaid** [comment]
nevermind, changing the dependencies does work

**Comment by Taskeren** [comment]
Cool! I've never thought that Fabric mods can run across versions!

~~So I just added the new code into 1.19 branch, lol. Nvm.~~

**Comment by Scarlaid** [comment]
I was so wrong, the harvesting function crashes the game on clicking

**Comment by Scarlaid** [comment]
![image](https://github.com/Taskeren/mineQuery-1.17/assets/90851437/6acf67fe-3e9b-4a50-a2e1-986b02596614)

so much for a hope :b

**Comment by Taskeren** [comment]
Fine, try the jar in [the latest action of branch 1.19](https://github.com/Taskeren/mineQuery-1.17/actions/runs/5369314619) then.

**Comment by Scarlaid** [comment]
The one you sent worked now, thanks and sorry if I was being annoying 🦆
![javaw_3ojq3FtcVN](https://github.com/Taskeren/mineQuery-1.17/assets/90851437/cb1d3bb4-4924-4014-a395-65cd16a8ac43)

**Comment by Taskeren** [comment]
No, not annoying at all!
It's my pleasure that my works are used by others!
