### ISSUE TITLE
[Feature Request] Adding an option to hold shift in order to break ungrowth crops

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#3]
The HarvestX is actually the best one from this mod so far, but I found that it's kinda annoying if you wanna break some crops that haven't fully grown yet, you have to go into the setting and turn the "Checking" off

My idea is if possible, whenever you want to break a not-fully-grown crop, hold shift to break it
There should be an option in the config menu to turn this feature on or off, for players

**Comment by Taskeren** [comment]
The feature has been added to the mod in latest build.
You can download it [here](https://github.com/Taskeren/mineQuery-1.17/actions/runs/2456709827).
