### ISSUE TITLE
Iron Golem isn't getting ignored

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#4]
I will leave this video here for further explaination: https://streamable.com/kn73qj

Basically, Iron Golem isn't ignoring damage with this mod, only the villager
Wrong video, fixed

**Comment by Taskeren** [comment]
Maybe it is a description mistake.
`ALL` means you can hit ALL of Iron Golems as the behavior is intended.

As I am not good at English, if you have any idea to improve the text, please let me know.

**Comment by Scarlaid** [comment]
The description said "Prevent Attack Iron Golem", "All" should have meant preventing the player hitting all the iron golem even natural or summoned by the player, not **able** to hit all the Golem

If you meant this config letting the players to hit all the golem then I would say "Allow player to hit Iron Golem"
That's the best I could go up with.
##### Despite the "Prevent Attack Villager" functioning like how the description said

**Comment by Scarlaid** [comment]
_Or keep the old description but changing the function do the opposite, to make it do exactly like the description_

**Comment by Taskeren** [comment]
The behavior has been changed in d3992e1.

**Comment by Scarlaid** [comment]
you forgot to upload it to Modrinth 😢

**Comment by Taskeren** [comment]
Uploaded.
I just forgot it xD.
