### ISSUE TITLE
"Auto Revive" seems to be causing crashes

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#6]
Crash log: [crash-2022-10-22_03.57.35-client.txt](https://github.com/Taskeren/mineQuery-1.17/files/9842453/crash-2022-10-22_03.57.35-client.txt)
I have spent solid of 1-2 hours to diagnose what is causing my game to crash whenever I die, until I realized I was in auto-revive state. 
MineQuery has this option, by default on, and somehow its quick respawning crash my game, however, turning it off and manually respawn doesn't crash

**Comment by Taskeren** [comment]
Well, I've tried to fix it, but I cannot find what's wrong. Can you provide your mods folder, please? the whole instance could be better.

For now, you can only disable it to prevent crashing.

**Comment by Scarlaid** [comment]
Alright, here is my modpack: https://github.com/Scarlaid/P-QoL/releases/download/v2.1.0/P-QoL-v2.1.0_1.19.2.zip
I'm currently using the Official Launcher with
- Azul (Zulu JDK) 17: https://www.azul.com/downloads/?package=jdk
- This Java Arguement: `-XX:+UseG1GC -Xmx3G -Xms3G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j2.formatMsgNoLookups=true`

**Comment by Scarlaid** [comment]
I found the problem, it was NVIDIA driver, it seems to be causing not only this but also Sodium/Litematica too https://github.com/CaffeineMC/sodium-fabric/issues/1486

Downgraded to 522.25 fixed this, so im gonna close this
