### ISSUE TITLE
"ReSeeding AC Flag"

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#8]
Separated issue from #7 

Anyway, I actually found [a mod](https://modrinth.com/mod/harvest) does the right-click reseeding function, which is normal to hear of course, but what significant is that somehow,  ***it does not tickle the anticheat***

For further explanation
- With Harvest spamming right-click: https://streamable.com/1gdq96
- With MineQuery's Reseeding spamming left-click: https://streamable.com/3niecd

Because I feel like using two mods for the same function is not ideal, so I think this could have a workaround.

> If information needed for the video
- The Anticheat was Vulcan being used 
- The Anticheat configurations are default
- Both were tested on a server with 82ms, not a big delay impact for most players

**Comment by Taskeren** [comment]
Giving the mod helps a lot!
I’ll take a look if I have time.

**Comment by Taskeren** [comment]
ReSeeding function in Harvest Mod is much different from mineQuery, so there is no easy way to implement like it.
I'll try to rewrite the whole feature to make both 2 ways can be selected in game.
Stay tuned.

**Comment by Taskeren** [comment]
New harvesting has been added in v1.7.2. I didn't test for anti-cheat as I don't have the ac plugin.
Let me know if it still triggers ac.

**Comment by Scarlaid** [comment]
Yeah the right-click harvesting worked without any Anti-cheat flags, while the old one, left-click harvesting, remain.
Right-click: https://streamable.com/94vwwr
Left-click: https://streamable.com/8w0pbc

Cheers for both options because now I can use any whenever I need to, inside or outside a server 😁

**Comment by Scarlaid** [comment]
you forgot to upload the mod to Modrinth btw xD
