### ISSUE TITLE
HarvestX/HarvestModLike Crop Check compatibility issue

### ISSUE THREAD

**Issue by Scarlaid** [Taskeren/mineQuery-1.17#9]
HarvestX, originally the main function from this mod, has crop checking for many plantings, especially not fully grown crops
HarvestModLike, which is HarvestRightClick, recently implemented into the mod to prevent Anti-cheat from flagging packets, broke the crop checking function, which ruined half the purpose of this mod

Two video below should show the issue, ignore the background noises
https://streamable.com/chye8o
https://streamable.com/hxt7al

**Comment by Taskeren** [comment]
Check out the new release.

**Comment by Scarlaid** [comment]
damn that was a clever workaround
the one thing right now about the right-click crop harvesting is it doesn't have a check if the players is holding a seed/plants or not, which is fairly inconvenient for players spamming their Bone Meal(s) to grow crops that aren't meant for breaking, rather a decoration (it's common for farm buildings)
This video should help: https://streamable.com/pwc5hz

But for now, thanks for accepting my issue and have a good holidays

**Comment by Taskeren** [comment]
There is no expected item holding check.
Maybe if turn Right Break off when holding nothing or what do you think about it?

Have a good holidays too. (But there is no actual break from work in China, lol)

**Comment by Scarlaid** [comment]
Ah right, China, people worked hard for a long period of time for a short break, gotta admire their spirit

Anyway, no, the video provided was having Right Break on
That's the issue I was trying to describe, basically it's for people trying to spam Bone Meal on crops, with this Right Clicking function, it would accidentally break the crops, which by any means, you have to replant it and hope for the best you won't accidentally break it again 💀

It's kinda a hard concept to describe with words, but I will try
*If there is like a checking for this function that the crops only break when the players is holding the seed/plants than is able to plant on crops then it would minimize the accidental breaking issue*

That's it I guess

**Comment by Taskeren** [comment]
To check the seed holding in hand is quite hard, because we don't know what are the seeds in code.

My thought is that like disabling right break when sneaking, or disabling when holding bone meal.
Which one would you like?

And I think we hardly use bone meal to make decorating crops, just turn it off can work all things out.

**Comment by Scarlaid** [comment]
I think keep it the same should be fair enough, think again I don't think people even spam Bone Meal that much except getting quick food.
